version: "3.8"
services:
  fastify_backend:
    container_name: fastify_backend
    image: fastify_backend_image
    build:
      context: .
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
